<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\Role;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function upUser(User $User)
    {
        $em = $this->getEntityManager();
        $UserRoles = $User->getUserRoles();
        
        foreach ($UserRoles as $URole){
            $User->removeRole($URole);
            $URole->removeUser($User);
            $em->persist($URole);
            $em->persist($User);
        }
        $em->persist($User);
        $em->flush();
        foreach ($User->getChanged() as $val)
        {
            $Role = $em->find(Role::class, $val);
            $User->addRole($Role);
            $Role->addUser($User);
            $em->persist($Role);
        }
        
       $em->flush();
    }
}
